export const deepLLanguages: Record<string, string> = {
  "be-BY": "RU",
  "cs-CZ": "CS",
  "da-DK": "DA",
  "de-DE": "DE",
  de: "DE",
  "en-US": "EN-US",
  en: "EN-US",
  "es-ES": "ES",
  "eu-ES": "ES",
  "fr-FR": "FR",
  fr: "FR",
  "hu-HU": "HU",
  "it-IT": "IT",
  "ja-JP": "JA",
  "lt-LT": "LT",
  "nl-NL": "NL",
  nl: "NL",
  "nn-NO": "NB",
  "pt-BR": "PT",
  "ro-RO": "RO",
  "ru-RU": "RU",
  "sk-SK": "SK",
  "sl-SI": "SL",
  "sv-SE": "SV",
  "uk-UA": "UK",
};
